cilium: Fix the eni value
rancher/rke2-charts pull request #146
Opened 2021-09-10 16:55 UTC by vadorovsky

The upstream Cilium chart changed the type of `eni` value to a nested
object. Adjust our rke2-cilium chart to that change.

Ref: #1615

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

2021-09-10 16:59 UTC, rancher-max approved these changes
LGTM

2021-09-10 17:18 UTC, brandond approved these changes

2021-09-10 17:19 UTC, brandond requested changes
Does the chart version need to be bumped too?

2021-09-13 07:38 UTC, vadorovsky commented
Yes, it does. I'm always forgetting about that. :facepalm:

2021-09-13 08:20 UTC, brandond approved these changes

2021-09-13 16:44 UTC, dereknola approved these changes

2021-09-13 16:44 UTC, merged