Update Cilium to v1.12.5 and Hubble to v0.10.0
rancher/rke2-charts pull request #320
Opened 2023-01-18 14:11 UTC by pjbgf

2023-01-18 16:11 UTC, brandond approved these changes

2023-01-18 16:28 UTC, rbrtbnfgl commented on packages/rke2-cilium/package.yaml
>  url: https://helm.cilium.io/cilium-1.12.4.tgz
```suggestion
url: https://helm.cilium.io/cilium-1.12.5.tgz
```

2023-01-18 16:28 UTC, rbrtbnfgl commented on packages/rke2-cilium/package.yaml
> +packageVersion: 03
```suggestion
packageVersion: 01
```

2023-01-18 16:28 UTC, brandond requested changes

2023-01-18 16:28 UTC, brandond commented on packages/rke2-cilium/package.yaml
>  url: https://helm.cilium.io/cilium-1.12.4.tgz
the chart version needs to be bumped to 1.12.5 as per https://github.com/rancher/rke2/pull/3802/files#r1073763146.

When doing this, please reset the packageVersion to 00.

2023-01-19 09:34 UTC, rbrtbnfgl commented
There are few file that you are patching but I think we don't need to patch. Probably you generated the patch from a `1.12.4` to a `1.12.5` and it generates the patch also to the modification done by Cilium.

2023-01-19 12:07 UTC, rbrtbnfgl commented
Do we need to change hubble-ui version on the chart? Usually we use the same version of the images from the source chart.

2023-01-19 14:59 UTC, pjbgf commented
That documentation comes from the Hubble repository: https://github.com/cilium/hubble#releases.

Potentially the reason why the chart hasn't been updated lately is that most folks use [cilium-cli](https://github.com/cilium/cilium-cli) for deploying Cilium and its sub-components.

2023-01-19 15:33 UTC, rbrtbnfgl approved these changes

2023-01-19 18:02 UTC, brandond approved these changes

2023-01-20 09:29 UTC, merged