rke2-snapshot-validation-webhook: Bump the chart version
rancher/rke2-charts pull request #357
Opened 2023-07-10 08:52 UTC by josedev-union

Current version is not validating requests to create/update `VolumeSnapshotClass` resources. This means it doesn't guarantee one default class.

Add VolumeSnapshotClass in the `validatingWebhookConfiguration`  resource list https://github.com/piraeusdatastore/helm-charts/pull/25

2023-07-13 17:37 UTC, brandond requested changes

2023-07-13 17:37 UTC, brandond commented on packages/rke2-snapshot-validation-webhook/package.yaml
> +packageVersion: 02
packageVersion should go back to 0 when bumping the release
```suggestion
packageVersion: 00
```

2023-07-13 23:04 UTC, brandond commented
Did you run `PACKAGE=rke2-snapshot-validation make patch` and confirm that our customizations apply cleanly to the new chart version? It appears that there are some conflicts.

2023-07-14 14:43 UTC, josedev-union commented
> Did you run `PACKAGE=rke2-snapshot-validation-webhook make prepare` and confirm that our customizations apply cleanly to the new chart version? It appears that there are some conflicts.
> 
> edit: I fixed it up for you and force-pushed. Still would appreciate if you could amend your commit to add sign-off.

@brandond please check again

2023-07-14 15:43 UTC, brandond approved these changes

2023-07-14 20:18 UTC, brandond commented
Thank you!

2023-07-14 20:18 UTC, merged