New runtimeclass chart
rancher/rke2-charts pull request #384
Opened 2023-11-30 00:15 UTC by vitorsavian

#### Proposed Changes ####

- New chart for nvidia runtime class and crun

#### Types of Changes ####

- New Feature

#### Verification ####

```bash
kubectl get runtimeclasses
```

#### Testing ####

#### Linked Issues ####

- https://github.com/k3s-io/k3s/issues/8700

#### User-Facing Change ####

```release-note
```

#### Further Comments ####

2023-11-30 22:15 UTC, brandond requested changes

2023-11-30 22:15 UTC, brandond commented on packages/rke2-runtimeclasses/charts/values.yaml
> +runtimeClass:
Nit: should this be plural?
```suggestion
runtimeClasses:
```

2023-11-30 22:15 UTC, brandond commented on packages/rke2-runtimeclasses/charts/templates/_helpers.tpl
> +{{/*
I think we can get rid of this file entirely. We're not generating names, not labeling or selecting anything, and don't use a service account. All we're doing is installing the RuntimeClass definitions which have fixed names and no labels.

2023-12-01 22:08 UTC, brandond approved these changes

2023-12-04 07:02 UTC, manuelbuil reviewed
what a simple chart! :D

2023-12-08 19:11 UTC, merged