Added updatecli and Canal update automation.
rancher/rke2-charts pull request #402
Opened 2024-02-07 13:10 UTC by rbrtbnfgl

This PR adds updatecli for version update automation with the update for the Canal charts.
The update for the Canal chart checks if a new image is released for flannel (https://github.com/rancher/image-build-flannel) and Calico (https://github.com/rancher/image-build-calico) and updates the image tag version.
`packageVersion` and the chart `version` are updated accordingly.

2024-02-07 13:44 UTC, thomasferrandiz approved these changes

2024-02-07 14:06 UTC, manuelbuil requested changes

2024-02-07 14:06 UTC, manuelbuil commented on updatecli/updatecli.d/updatecanal.yaml
> +      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
Try using this instead https://github.com/rancher/image-build-cni-plugins/blob/main/updatecli/updatecli.d/updateplugins.yaml#L11

2024-02-07 14:06 UTC, manuelbuil commented on updatecli/updatecli.d/updatecanal.yaml
> +      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
I don't think we need username here

2024-02-07 14:06 UTC, manuelbuil commented on updatecli/updatecli.d/updatecanal.yaml
> +      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
Use this instead: https://github.com/rancher/image-build-cni-plugins/blob/main/updatecli/updatecli.d/updateplugins.yaml#L45-L46, that way we use values.yaml

2024-02-07 14:06 UTC, manuelbuil commented on updatecli/updatecli.d/updatecli.yml
> +# This small test makes sure that updatecli is working properly on a repo.
Do you think we need this yaml file, I thought it was just for testing

2024-02-08 14:12 UTC, manuelbuil approved these changes

2024-02-08 16:07 UTC, merged