cilium: Make the wait-for-note-init container privileged
rancher/rke2-charts pull request #75
Opened 2021-04-30 15:25 UTC by mrostecki

Before this change, wait-for-node-init container was not able to execute
properly with SELinux enabled, due to lack of ability to access the bind
mounted file. Due to lack of ability to set the container_file_t label
through Kubernetes, the other possible solution, done in this commit, is
making the container privileged. All the other containers accessing the
bootstrap file are already privileged as well, so it should not be that
harmful.

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

2021-04-30 16:21 UTC, rancher-max commented
https://github.com/rancher/rke2/issues/931

2021-04-30 21:44 UTC, brandond requested changes
Chart version needs to be bumped.

2021-05-03 16:54 UTC, mrostecki commented
@brandond Thanks. I bumped the version, but CI still fails with

```
time="2021-05-03T14:49:38Z" level=fatal msg="Failed to validate against main: Hash of new contents at new-assets/charts-without-rc/rke2-cilium/rke2-cilium/1.9.603 does not match that of old contents at original-assets/charts/rke2-cilium/rke2-cilium/1.9.603"
```

Any idea why I still get this error?

The only thing I want to achieve with this PR is adding the following lines to the cilium-agent-daemonset template:

```patch
+        securityContext:
+          privileged: true
```

2021-05-03 17:57 UTC, mrostecki commented
It passes now, @brandond please disregard my previous comment.

2021-05-03 19:18 UTC, brandond approved these changes

2021-05-04 08:26 UTC, merged